name: Windows x64

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [tismuslauncher]
  workflow_dispatch:
    inputs:
      build-type:
        description: Type of build (Debug or Release)
        type: choice
        options:
          - Release
          - Debug
        default: Release

permissions: {}

jobs:
  build:
    name: Build (Windows-MSVC-x64)
    runs-on: windows-2022

    permissions:
      contents: read
      id-token: write
      packages: write

    env:
      ARTIFACT_NAME: Windows-MSVC-Qt6
      BUILD_PLATFORM: official
      BUILD_TYPE: ${{ inputs.build-type || 'Release' }}
      CMAKE_PRESET: windows_msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup dependencies
        id: setup-dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          build-type: ${{ env.BUILD_TYPE }}
          artifact-name: Windows-MSVC
          vcvars-arch: amd64
          qt-version: 6.11.2

      - name: Configure project
        shell: bash
        run: |
          cmake --preset "$CMAKE_PRESET" -D VCPKG_HOST_TRIPLET="$VCPKG_TRIPLET" -D VCPKG_TARGET_TRIPLET="$VCPKG_TRIPLET"

      - name: Run build
        shell: bash
        run: cmake --build --preset "$CMAKE_PRESET" --config "$BUILD_TYPE"

      - name: Run tests
        shell: bash
        run: ctest --preset "$CMAKE_PRESET" --build-config "$BUILD_TYPE"

      - name: Get short version
        id: short-version
        shell: bash
        run: echo "version=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Package (Windows)
        uses: ./.github/actions/package/windows
        env:
          CI_HAS_ACCESS_TO_AZURE: ${{ vars.CI_HAS_ACCESS_TO_AZURE || '' }}
        with:
          version: ${{ steps.short-version.outputs.version }}
          build-type: ${{ steps.setup-dependencies.outputs.build-type }}
          artifact-name: Windows-MSVC
          msystem: ''
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
